# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/sm7250-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter monet picasso vangogh gauguin,$(TARGET_DEVICE)),)

endif
